# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 157ec76d5ba18c024c9a2b5eb5f93b45350578af151e6c81cd2358ae7da52bc7c6502b036e7863881c575bd8f497226dfe7ac8e3c8301a48892fb295509f3d62

test:
  secret_key_base: 402317ac50861138d7c8b24994b33cf9509e07aeda14d10dc6d6caade4837bf4bb968c1db63703e0ee06169bd1ba16258fc5d1fc66982a3ab47e8f10b2b8315f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
